### ISSUE TITLE
Choose a better license

### ISSUE THREAD

**Issue by wmcgonagle** [jibsen/parg#3]
Currently, the CC0 license is [NOT recommended](https://opensource.org/faq#cc-zero) by the Open Source Initiative due to a clause that could "possibly even weaken patent infringement defenses available to users of software released under CC0." For this reason I highly recommend that a switch to a public domain equivalent license such as the [Zero-Clause BSD license](https://opensource.org/licenses/0BSD) be made.

**Comment by jibsen** [comment]
Firstly, thank you for taking the time to raise this issue.

I think "better" is perhaps a bit subjective, but acknowledge there appears to be some concerns about parts of CC0.

I haven't found a reasonable alternative (palatable to companies, accepted by open source organizations, popular enough that most people will know what it means). It looks like 0BSD is slowly gaining a little traction in those areas.

**Comment by wmcgonagle** [comment]
I do agree that the term "better" in this situation is a little subjective, I couldn't think of a better term and I apologize if I came off as commanding or pretentious. If 0BSD is not appealing to you perhaps MIT No Attribution [\[0\]](https://opensource.org/licenses/MIT-0) [\[1\]](https://spdx.org/licenses/MIT-0.html) will be a little more appealing. In the end this is your project and if you are happy with your current license I am perfectly okay with closing this issue.

\[0\] https://opensource.org/licenses/MIT-0
\[1\] https://spdx.org/licenses/MIT-0.html

**Comment by jibsen** [comment]
I welcome the discussion!

I wasn't aware of the 0BSD and MIT-0 licenses, and have been reading up on what has been happening with public domain equivalent licensing (including a detour into [SPDX IDs](https://spdx.dev/ids/)) -- it has been very interesting.

I wouldn't be against changing to one of those (assuming there are no objections raised). I don't currently have a strong preference for either, I will ponder it some more.

**Comment by jibsen** [comment]
So, there are a lot of interesting aspects in this. With the disclaimer that I am not a lawyer, and most of this is based on "reading stuff on the internet", here are some thoughts on these two licenses.

### 0BSD

Based on the [ISC license](https://en.wikipedia.org/wiki/ISC_license), which according to Wikipedia is similar to the BSD-2-Clause and MIT licenses, but "without language deemed unnecessary following the Berne Convention". While it is nice that it is slightly shorter, I must admit I don't know the specifics of the Berne Convention offhand.

0BSD is based on the updated version of the ISC license from 2007 (where "and" was changed to "and/or"), while OpenBSD appears to [deliberately use](https://marc.info/?l=openbsd-misc&m=120618313520730) the original version. I don't know if it makes any difference.

#### Popularity

There are currently 1,315 packages licensed under 0BSD on [libraries.io](https://libraries.io/licenses/0BSD).

Searching on GitHub shows 51,552 repositories using the 0BSD license. It seemed a bit odd to me that about 34k of those were JavaScript, but it appears they are mostly based on some default boilerplate from a framework called Gatsby. If you search for "license:0bsd NOT gatsby" you get 23,521 repositories.

#### Corporate Adoption

The 0BSD license is used by the toybox project, which is included in Android. Microsoft changed the license of tslib to 0BSD. The Google [licensing guidelines](https://opensource.google/documentation/reference) allows them to use and contribute to 0BSD licensed projects, with no mention of MIT-0 yet.

### MIT-0

Based on the MIT license, which is popular and relatively well understood (though some gloss over the requirement to include the notice).

#### Popularity

There are currently 356 packages licensed under MIT-0 on [libraries.io](https://libraries.io/licenses/MIT-0).

Searching GitHub shows 5,207 repositories using the MIT-0 license. If you search for "license:mit-0 NOT aws" you get 3,148 repositories.

#### Corporate Adoption

AWS uses the MIT-0 license extensively for their example code on GitHub.

### Concerns

The MIT license includes an explicit right to sublicense. As I understand it, this is [not necessary](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html) because, like most open source licenses, it requires you to include the notice, which gives anyone obtaining a copy a direct license. It is not clear to me if/how this changes when the requirement to include the notice is removed.

If someone uses your code but does not include the license notice (which these licenses do not require), then the warranty disclaimer and limitation of liability are not included either. I don't know if this could potentially [be an issue](https://writing.kemitchell.com/2020/12/27/War-on-License-Notices). In the case of the MIT-0 license you could perhaps argue not including the notice is sublicensing.

Given that both licenses appear to be accepted by the legal team of a large corporation, these concerns may be silly.

### Current View

The 0BSD license is more used at the moment, and I like that it has been accepted by Google, but I feel more comfortable with the MIT-0 license.

**Comment by jibsen** [comment]
I've decided to go with the MIT No Attribution license ([MIT-0](https://opensource.org/license/mit-0/)).

Thanks again for raising this issue!
